name: Free-For-All
main: com.caved_in.freeforall.Game
version: 1.0
description: Free for all - It's dog eat dog out there!
author: Brandon Curtis
depend: [Multiverse-Core,TagAPI,PopupMenuAPI,CrackShot,WorldManager,ForceRespawn,Tunnels-Common]
commands:
   addspawn:
      usage: /<command> <team>
      permission: op
   forcemap:
      usage: /<command> <map>
      permission: op
   forcewin:
      usage: /<command>
      permission: op
   kit:
      usage: /<command>
   loadout:
      usage: /<command>
   afk:
      usage: /<command>
   game:
      usage: /<command>
   spawns:
      usage: /<command>
   maps:
      usage: /<command>
   gem:
      usage: /<command>